module.exports = {
  tt15239678: {
    imdbID: "tt15239678",
    Title: "Dune: Part Two",
    Released: "2024-03-01",
    Runtime: 166,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Denis Villeneuve"],
    Writers: ["Denis Villeneuve", "Jon Spaihts", "Frank Herbert"],
    Actors: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    Plot: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    Poster: "https://preview.redd.it/official-poster-for-dune-part-two-v0-99a79xg2yfxa1.jpg?auto=webp&s=06487fa78a1fe075161c518bd50993e35d394c25",
    Metascore: 79,
    imdbRating: 8.6,
  },
  tt0117951: {
    imdbID: "tt0117951",
    Title: "Trainspotting",
    Released: "1996-02-23",
    Runtime: 94,
    Genres: ["Drama"],
    Directors: ["Danny Boyle"],
    Writers: ["Irvine Welsh", "John Hodge"],
    Actors: ["Ewan McGregor", "Ewen Bremner", "Jonny Lee Miller"],
    Plot: "Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.",
    Poster: "https://www.fbw-filmbewertung.com/uploads/fbwdb_film/poster/c3f3d9a3a8918eb0120e2570e2051a6dee7c39f5.jpg",
    Metascore: 83,
    imdbRating: 8.1,
  },
  tt0942385: {
    imdbID: "tt0942385",
    Title: "Tropic Thunder",
    Released: "2008-08-13",
    Runtime: 107,
    Genres: ["Action", "Comedy"],
    Directors: ["Ben Stiller"],
    Writers: ["Justin Theroux", "Ben Stiller", "Etan Cohen"],
    Actors: ["Ben Stiller", "Jack Black", "Robert Downey Jr."],
    Plot: "Through a series of freak occurrences, a group of actors shooting a big-budget war movie are forced to become the soldiers they are portraying.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNDE5NjQzMDkzOF5BMl5BanBnXkFtZTcwODI3ODI3MQ@@._V1_.jpg",
    Metascore: 71,
    imdbRating: 7.1,
  },
  tt6751668: {
    imdbID: "tt6751668",
    Title: "Parasite",
    Released: "2019-05-30",
    Runtime: 132,
    Genres: ["Drama", "Thriller"],
    Directors: ["Bong Joon Ho"],
    Writers: ["Bong Joon Ho", "Han Jin-won"],
    Actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Poster: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    Metascore: 96,
    imdbRating: 8.5,
  },
  tt17351924: {
    imdbID: "tt17351924",
    Title: "Saltburn",
    Released: "2023-11-17",
    Runtime: 131,
    Genres: ["Comedy", "Drama", "Thriller"],
    Directors: ["Emerald Fennell"],
    Writers: ["Emerald Fennell"],
    Actors: ["Barry Keoghan", "Jacob Elordi", "Rosamund Pike"],
    Plot: "A student at Oxford University finds himself drawn into the world of a charming and aristocratic classmate, who invites him to his eccentric family's sprawling estate.",
    Poster: "https://de.web.img3.acsta.net/pictures/23/10/30/10/42/2454871.jpg",
    Metascore: 61,
    imdbRating: 7.0,
  },
  tt0108358: {
    imdbID: "tt0108358",
    Title: "Tombstone",
    Released: "1993-12-25",
    Runtime: 130,
    Genres: ["Action", "Biography", "Drama"],
    Directors: ["George P. Cosmatos", "Kevin Jarre"],
    Writers: ["Kevin Jarre"],
    Actors: ["Kurt Russell", "Val Kilmer", "Sam Elliott"],
    Plot: "A successful lawman's plans to retire anonymously in Tombstone, Arizona are disrupted by the kind of outlaws he was famous for eliminating.",
    Poster: "https://m.media-amazon.com/images/I/81PxPKXGiML.jpg",
    Metascore: 50,
    imdbRating: 7.8,
  }
};